-- Add sample educational content
INSERT INTO educational_content (title, content, category, author) VALUES
('Understanding Cervical Cancer', 'Cervical cancer is a type of cancer that occurs in the cells of the cervix — the lower part of the uterus that connects to the vagina. Various strains of the human papillomavirus (HPV), a sexually transmitted infection, play a role in causing most cervical cancer cases.', 'General', 'Medical Team'),
('HPV and Cervical Cancer', 'Human papillomavirus (HPV) is the main cause of cervical cancer. HPV is a common virus that is passed from one person to another during sex. At least half of sexually active people will have HPV at some point in their lives, but few women will get cervical cancer.', 'Prevention', 'Medical Team'),
('Screening and Early Detection', 'Regular screening can help detect cervical cancer early when treatment is most effective. The Pap test (or Pap smear) looks for precancers, cell changes on the cervix that might become cervical cancer if they are not treated appropriately.', 'Screening', 'Medical Team'),
('Treatment Options', 'Treatment for cervical cancer depends on the stage and type of cancer. Options may include surgery, radiation therapy, chemotherapy, targeted therapy, or immunotherapy. Your healthcare team will work with you to develop the best treatment plan.', 'Treatment', 'Medical Team'),
('Living with Cervical Cancer', 'Managing symptoms and maintaining quality of life during and after treatment is important. This includes managing side effects, staying active, eating well, and getting emotional support from family, friends, or support groups.', 'Support', 'Medical Team'),
('Prevention Through Vaccination', 'HPV vaccines can prevent infection with the types of HPV that most commonly cause cervical cancer. The vaccine is most effective when given before a person becomes sexually active.', 'Prevention', 'Medical Team'),
('Symptoms to Watch For', 'Early cervical cancer generally produces no signs or symptoms. Signs and symptoms of more-advanced cervical cancer include vaginal bleeding after intercourse, between periods or after menopause, watery, bloody vaginal discharge that may be heavy and have a foul odor, and pelvic pain.', 'Symptoms', 'Medical Team');
